"""allow_null_email_and_id_card

Revision ID: allow_null_email_and_id_card
Revises:
Create Date: 2025-11-13 02:51:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'allow_null_email_and_id_card'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 修改users表的email字段，允许为NULL
    op.alter_column('users', 'email',
                  existing_type=sa.String(length=120),
                  nullable=True,
                  existing_nullable=False)

    # 移除email字段的UNIQUE约束
    op.drop_index('ix_users_email', table_name='users')

    # 为非空的email创建新的索引
    op.create_index('ix_users_email_partial', 'users',
                     ['email'], unique=True,
                     postgresql_where=sa.text("email IS NOT NULL AND email != ''"),
                     sqlite_where=sa.text("email IS NOT NULL AND email != ''"))

    # 修改alumni_profiles表的id_card字段，允许为NULL
    op.alter_column('alumni_profiles', 'id_card',
                  existing_type=sa.String(length=20),
                  nullable=True,
                  existing_nullable=False)

    # 移除id_card字段的UNIQUE约束
    op.drop_index('uq_alumni_profiles_id_card', table_name='alumni_profiles')

    # 为非空的id_card创建新的索引
    op.create_index('uq_alumni_profiles_id_card_partial', 'alumni_profiles',
                     ['id_card'], unique=True,
                     postgresql_where=sa.text("id_card IS NOT NULL AND id_card != ''"),
                     sqlite_where=sa.text("id_card is not null and id_card != ''"))

    # 将现有的空字符串转换为NULL
    op.execute("UPDATE users SET email = NULL WHERE email = ''")
    op.execute("UPDATE alumni_profiles SET id_card = NULL WHERE id_card = ''")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # 将NULL值恢复为空字符串
    op.execute("UPDATE users SET email = '' WHERE email IS NULL")
    op.execute("UPDATE alumni_profiles SET id_card = '' WHERE id_card IS NULL")

    # 删除部分索引
    op.drop_index('uq_alumni_profiles_id_card_partial', table_name='alumni_profiles')
    op.drop_index('ix_users_email_partial', table_name='users')

    # 恢复UNIQUE约束
    op.create_unique_constraint('alumni_profiles', 'uq_alumni_profiles_id_card', ['id_card'])
    op.create_unique_constraint('users', 'uq_users_email', ['email'])

    # 修改字段为非空
    op.alter_column('alumni_profiles', 'id_card',
                  existing_type=sa.String(length=20),
                  nullable=False)
    op.alter_column('users', 'email',
                  existing_type=sa.String(length=120),
                  nullable=False)