"""Update alumni profile: change department to division and add division_director field

Revision ID: bc49761fa646
Revises: 
Create Date: 2025-10-15 23:18:42.437699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc49761fa646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加新字段，允许NULL
    op.add_column('alumni_profiles', sa.Column('division', sa.String(length=100), nullable=True))
    op.add_column('alumni_profiles', sa.Column('division_director', sa.String(length=100), nullable=True))

    # 2. 数据迁移：将department数据迁移到division
    op.execute("UPDATE alumni_profiles SET division = department WHERE division IS NULL AND department IS NOT NULL")

    # 3. 将NULL的division设置为默认值
    op.execute("UPDATE alumni_profiles SET division = '未分类' WHERE division IS NULL")

    # 4. 使用批量操作修改字段约束和删除旧字段
    with op.batch_alter_table('alumni_profiles', schema=None) as batch_op:
        batch_op.alter_column('division', existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.alter_column('major',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('dean')
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('dean', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('major',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('division_director')
        batch_op.drop_column('division')

    # ### end Alembic commands ###
