"""Add dining_companions field to alumni_profiles

Revision ID: d4342a3ce55d
Revises: 6397de81a78a
Create Date: 2025-11-11 20:29:08.179496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4342a3ce55d'
down_revision = '6397de81a78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dining_companions', sa.Integer(), nullable=True))

    with op.batch_alter_table('face_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_history_user_id'))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['leader_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['head_teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['class_teacher_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('is_visitable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_class_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['student_parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['parent_student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.alter_column('is_class_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_visitable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('face_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['verification_admin_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_face_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('alumni_profiles', schema=None) as batch_op:
        batch_op.drop_column('dining_companions')

    # ### end Alembic commands ###
