"""add school calendar and event booking models

Revision ID: 9feae9648337
Revises: bc49761fa646
Create Date: 2025-10-16 06:14:20.897344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9feae9648337'
down_revision = 'bc49761fa646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='事件标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件描述'),
    sa.Column('event_type', sa.Enum('anniversary', 'festival', 'activity', 'club', 'holiday', 'exam', 'meeting'), nullable=False, comment='事件类型'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='结束时间'),
    sa.Column('all_day', sa.Boolean(), nullable=True, comment='是否全天事件'),
    sa.Column('target_audience', sa.Enum('all', 'alumni', 'students', 'teachers', 'specific'), nullable=True, comment='目标受众'),
    sa.Column('target_graduation_years', sa.String(length=500), nullable=True, comment='目标毕业年份（逗号分隔）'),
    sa.Column('target_divisions', sa.String(length=500), nullable=True, comment='目标学部（逗号分隔）'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='活动地点'),
    sa.Column('online_url', sa.String(length=500), nullable=True, comment='在线链接'),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent'), nullable=True, comment='重要程度'),
    sa.Column('status', sa.Enum('draft', 'published', 'cancelled', 'completed'), nullable=True, comment='状态'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('requires_booking', sa.Boolean(), nullable=True, comment='是否需要预约'),
    sa.Column('max_participants', sa.Integer(), nullable=True, comment='最大参与人数'),
    sa.Column('booking_deadline', sa.DateTime(), nullable=True, comment='预约截止时间'),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('club_name', sa.String(length=100), nullable=True, comment='社团名称'),
    sa.Column('club_type', sa.Enum('academic', 'sports', 'arts', 'volunteer', 'technology', 'other'), nullable=True, comment='社团类型'),
    sa.Column('anniversary_year', sa.Integer(), nullable=True, comment='周年纪念年数（如10、20、30）'),
    sa.Column('graduation_year', sa.Integer(), nullable=True, comment='对应毕业年份'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_time', sa.DateTime(), nullable=True, comment='预约时间'),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'attended', 'no_show'), nullable=True, comment='预约状态'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['school_calendar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_bookings')
    op.drop_table('school_calendar')
    # ### end Alembic commands ###
