"""add access_code to visit_applications

Revision ID: add_access_code
Revises:
Create Date: 2026-03-28

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_access_code'
down_revision = None  # TODO: set this to the previous migration ID


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_applications', sa.Column('access_code', sa.String(20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_applications', 'access_code')
    # ### end Alembic commands ###
